"""QGroundControl overlay generation helpers."""

from __future__ import annotations

import json
from pathlib import Path

from .models import Solution

_DRONE_COLORS = [
    "#D1495B",
    "#00798C",
    "#EDAe49",
    "#30638E",
    "#6A994E",
    "#9C6644",
]


def _overlay_filename(overlay_name: str) -> str:
    sanitized = "".join(
        ch.lower() if ch.isalnum() else "_"
        for ch in overlay_name.strip()
    )
    sanitized = "_".join(part for part in sanitized.split("_") if part)
    if not sanitized:
        sanitized = "dronevalkit_overlay"
    return f"{sanitized}.qml"


def render_qgc_overlay_qml(
    solution: Solution,
    overlay_name: str = "dronevalkit overlay",
) -> str:
    """Render a QGroundControl-friendly QML map overlay for a solution.

    The generated component uses ``MapItemGroup`` as the root so it can be
    instantiated inside a QGroundControl map view or another QtLocation map.
    It visualizes:

    - the truck route as a polyline
    - each drone sortie as a colored polyline
    - labeled markers for depot, customers, launch, delivery, and rendezvous nodes
    """

    def _node_to_gps(node_id: int) -> tuple[float, float]:
        if node_id == 0:
            return solution.problem.depot
        return solution.problem.customers[node_id]

    def _coord_payload(lat: float, lon: float) -> dict[str, float]:
        return {"lat": float(lat), "lon": float(lon)}

    def _marker_payload(
        lat: float,
        lon: float,
        label: str,
        color: str,
        size: int,
    ) -> dict[str, object]:
        return {
            "lat": float(lat),
            "lon": float(lon),
            "label": label,
            "color": color,
            "size": int(size),
        }

    truck_path = [_coord_payload(*_node_to_gps(node_id)) for node_id in solution.truck_route]
    polylines: list[dict[str, object]] = [
        {
            "label": "Truck Route",
            "color": "#202020",
            "width": 4,
            "path": truck_path,
        }
    ]

    markers: list[dict[str, object]] = []
    depot_lat, depot_lon = solution.problem.depot
    markers.append(_marker_payload(depot_lat, depot_lon, "Depot", "#111111", 18))

    for node_id in sorted(solution.problem.customers):
        lat, lon = solution.problem.customers[node_id]
        label = f"Customer {node_id}"
        color = "#2D6A4F" if node_id in solution.problem.drone_eligible else "#6C757D"
        markers.append(_marker_payload(lat, lon, label, color, 14))

    for sortie_index, sortie in enumerate(solution.sorties):
        launch_node = solution.launch_node(sortie_index)
        launch = _node_to_gps(launch_node)
        delivery = _node_to_gps(sortie.delivery)
        rendezvous = _node_to_gps(sortie.rendezvous)
        color = _DRONE_COLORS[sortie.drone_id % len(_DRONE_COLORS)]

        polylines.append(
            {
                "label": f"Sortie {sortie_index} (drone {sortie.drone_id})",
                "color": color,
                "width": 3,
                "path": [
                    _coord_payload(*launch),
                    _coord_payload(*delivery),
                    _coord_payload(*rendezvous),
                ],
            }
        )

        markers.append(
            _marker_payload(
                launch[0],
                launch[1],
                f"S{sortie_index} launch n{launch_node} d{sortie.drone_id}",
                color,
                12,
            )
        )
        markers.append(
            _marker_payload(
                delivery[0],
                delivery[1],
                f"S{sortie_index} delivery n{sortie.delivery} d{sortie.drone_id}",
                color,
                12,
            )
        )
        markers.append(
            _marker_payload(
                rendezvous[0],
                rendezvous[1],
                f"S{sortie_index} rv n{sortie.rendezvous} d{sortie.drone_id}",
                color,
                12,
            )
        )

    polylines_json = json.dumps(polylines, indent=2)
    markers_json = json.dumps(markers, indent=2)
    overlay_name_json = json.dumps(str(overlay_name))

    return f"""import QtQuick 2.15
import QtLocation 5.15
import QtPositioning 5.15

MapItemGroup {{
    id: root

    // Generated by dronevalkit.render_qgc_overlay_qml / save_qgc_overlay.
    // Intended for use as a custom map overlay component in QGroundControl.
    readonly property string overlayName: {overlay_name_json}
    readonly property var polylines: {polylines_json}
    readonly property var markers: {markers_json}

    Repeater {{
        model: root.polylines

        delegate: MapPolyline {{
            line.width: modelData.width
            line.color: modelData.color
            path: modelData.path.map(function(point) {{
                return QtPositioning.coordinate(point.lat, point.lon)
            }})
        }}
    }}

    Repeater {{
        model: root.markers

        delegate: MapQuickItem {{
            coordinate: QtPositioning.coordinate(modelData.lat, modelData.lon)
            anchorPoint.x: marker.width / 2
            anchorPoint.y: marker.height / 2

            sourceItem: Item {{
                id: marker
                width: labelBubble.width
                height: labelBubble.height

                Rectangle {{
                    id: labelBubble
                    radius: 8
                    color: "#F7F7F7"
                    border.color: modelData.color
                    border.width: 2
                    opacity: 0.92
                    implicitWidth: labelRow.width + 12
                    implicitHeight: labelRow.height + 8

                    Row {{
                        id: labelRow
                        spacing: 6
                        anchors.centerIn: parent

                        Rectangle {{
                            width: modelData.size
                            height: modelData.size
                            radius: width / 2
                            color: modelData.color
                        }}

                        Text {{
                            text: modelData.label
                            color: "#111111"
                            font.pixelSize: 12
                        }}
                    }}
                }}
            }}
        }}
    }}
}}
"""


def save_qgc_overlay(
    solution: Solution,
    path: str | None = None,
    overlay_name: str = "dronevalkit overlay",
) -> str:
    """Write a QGroundControl overlay QML file.

    Returns the generated file path. If *path* is omitted, a filename is
    derived from *overlay_name* in the current directory.
    """
    qml = render_qgc_overlay_qml(solution, overlay_name=overlay_name)
    if path is None:
        output_path = Path.cwd() / _overlay_filename(overlay_name)
    else:
        output_path = Path(path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(qml, encoding="utf-8")
    return str(output_path)
